#version: 2.1
#orbs:
#  node: circleci/node@3.0.0
#workflows:
#  node-tests:
#    jobs:
#      - node/test

version: 2

jobs:
  lint-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run:
          name: Install packages
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
           - node_modules

      - run:
          name: Run linter
          command: eslint --ext .js,.vue src
#      - run:
#          name: Run tests
#          command: echo "This is just sample config, please replace this command with real tests :)"
#      - run:
#          name: Build and minify app
#          command: yarn build
#      - run:
#          name: Deploy to AWS S3
#          command: yarn deploy
workflows:
  version: 2
  main:
    jobs:
      - lint-and-deploy



